check_updates: true

# Having every single item parsed may be intense for the server.
# Enabling this option will cause items without item meta to be skipped, with exception to the given
# item types
skip_no_meta_items: true
exceptions:
  - WOODEN_SWORD
  - WOODEN__AXE
  - WOODEN__PICKAXE
  - WOODEN__SHOVEL
  - WOODEN__HOE
  - STONE_SWORD
  - STONE_AXE
  - STONE_PICKAXE
  - STONE_SHOVEL
  - STONE_HOE
  - IRON_SWORD
  - IRON_AXE
  - IRON_PICKAXE
  - IRON_SHOVEL
  - IRON_HOE
  - GOLDEN_SWORD
  - GOLDEN_AXE
  - GOLDEN_PICKAXE
  - GOLDEN_SHOVEL
  - GOLDEN_HOE
  - DIAMOND_SWORD
  - DIAMOND_AXE
  - DIAMOND_PICKAXE
  - DIAMOND_SHOVEL
  - DIAMOND_HOE
  - NETHERITE_SWORD
  - NETHERITE_AXE
  - NETHERITE_PICKAXE
  - NETHERITE_SHOVEL
  - NETHERITE_HOE
  - LEATHER_HELMET
  - LEATHER_CHESTPLATE
  - LEATHER_LEGGINGS
  - LEATHER_BOOTS
  - CHAINMAIL_HELMET
  - CHAINMAIL_CHESTPLATE
  - CHAINMAIL_LEGGINGS
  - CHAINMAIL_BOOTS
  - IRON_HELMET
  - IRON_CHESTPLATE
  - IRON_LEGGINGS
  - IRON_BOOTS
  - GOLDEN_HELMET
  - GOLDEN_CHESTPLATE
  - GOLDEN_LEGGINGS
  - GOLDEN_BOOTS
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  - NETHERITE_HELMET
  - NETHERITE_CHESTPLATE
  - NETHERITE_LEGGINGS
  - NETHERITE_BOOTS
  - TURTLE_HELMET
  - FISHING_ROD
  - TRIDENT
  - MACE
  - SHIELD
  - SHEARS
  - ELYTRA
  - BRUSH
  - FLINT_AND_STEEL
  - CARROT_ON_A_STICK
  - WARPED_FUNGUS_ON_A_STICK



